mutation($id: Int!, $destinationPath: String!, $destinationLocale: String!, $reuseHistoricalPath: Boolean!) {
  pages {
    move(id: $id, destinationPath: $destinationPath, destinationLocale: $destinationLocale, reuseHistoricalPath: $reuseHistoricalPath) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
